VIRTUAL_WIDTH = 640
VIRTUAL_HEIGHT = 480

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 960

TILES_PER_ROW = 8
TILE_SIZE = 32

BOARD_X_OFFSET = (VIRTUAL_WIDTH - TILES_PER_ROW * TILE_SIZE)/2
BOARD_Y_OFFSET = (VIRTUAL_HEIGHT - TILES_PER_ROW * TILE_SIZE)/4

DIRS = {}

DIR_UP = vector(0, -1)
DIR_RIGHT = vector(1, 0)
DIR_DOWN = vector(0, 1)
DIR_LEFT = vector(-1, 0)

COLOR_BLACK = {0,0,0}